Repository hekkaaa/Bear-goodbye-kolkhoz, pull requests merged in 2022-03, with the labels that each got.

#68 BGK-34
  BGK.Data/Migrations/20220226162505_new-tables.Designer.cs
  BGK.Data/Migrations/20220226162505_new-tables.cs
  BearGoodbyeKolkhoz.API/Controllers/AdminsController.cs
  BearGoodbyeKolkhoz.API/Controllers/CompaniesController.cs
  BearGoodbyeKolkhoz.API/Controllers/EventsController.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
Labels: invalid

#80 Bgk 53
  BGK.Business/Models/CompanyModel.cs
  BGK.Business/Services/CompanyService.cs
  BGK.Business/Services/Interfaces/ICompanyService.cs
  BGK.Data/Entities/Company.cs
  BGK.Data/Migrations/20220306131342_AddBigIntForTin.Designer.cs
  BGK.Data/Migrations/20220306131342_AddBigIntForTin.cs
  BGK.Data/Migrations/ApplicationContextModelSnapshot.cs
  BearGoodbyeKolkhoz.API/Configuration/ExceptionResponse/ValidationExceptionResponse.cs
  BearGoodbyeKolkhoz.API/Controllers/CompaniesController.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/CompanyInputModel.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/CompanyInsertInputModel.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/CompanyUpdateInputModel.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/CompanyOutputModel.cs
Labels: bug

#82 BGK-56
  BGK.Business/Exceptions/UnexpectedErrorServerException.cs
  BGK.Business/Services/Interfaces/ILecturerService.cs
  BGK.Business/Services/LecturerService.cs
  BGK.Data/Repositories/Interfaces/ILecturerRepository.cs
  BGK.Data/Repositories/LecturerRepository.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
  BearGoodbyeKolkhoz.API/Infrastructure/ErrorHandlerMiddleware.cs
Labels: bug

#81 BGK-46
  BearGoodbyeKolkhoz.API/Controllers/ClientsController.cs
Labels: bug

#83 Bgk 52
  BGK.Business/Services/ClientService.cs
  BGK.Business/Services/Interfaces/IClientService.cs
  BGK.Data/Repositories/ClientRepository.cs
  BearGoodbyeKolkhoz.API/Configuration/APIMapperProfile.cs
  BearGoodbyeKolkhoz.API/Controllers/ClientsController.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/ClientInputModel.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/ClientOutputModel.cs
Labels: bug

#87 BGK-69 Переделал юрл и чуточку поменял описание для сваггера
  BearGoodbyeKolkhoz.API/Controllers/AdminsController.cs
  BearGoodbyeKolkhoz.API/Controllers/ClassroomsController.cs
  BearGoodbyeKolkhoz.API/Controllers/ClientsController.cs
  BearGoodbyeKolkhoz.API/Controllers/CompaniesController.cs
  BearGoodbyeKolkhoz.API/Controllers/EventsController.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
  BearGoodbyeKolkhoz.API/Controllers/TopicsController.cs
  BearGoodbyeKolkhoz.API/Controllers/TrainingsController.cs
Labels: bug

#90 BGK 82
  BGK.Business/Configuration/BusinessMapperProfile.cs
  BGK.Business/Models/UserModel.cs
  BGK.Business/Services/AdminService.cs
  BGK.Business/Services/ClientService.cs
  BGK.Business/Services/CompanyService.cs
  BGK.Business/Services/Interfaces/IAdminService.cs
  BGK.Business/Services/Interfaces/IClientService.cs
  BGK.Business/Services/Interfaces/ICompanyService.cs
  BGK.Business/Services/Interfaces/ILecturerService.cs
  BGK.Business/Services/Interfaces/IUserService.cs
  BGK.Business/Services/LecturerService.cs
  BGK.Business/Services/UserService.cs
  BGK.Data/Repositories/AdminRepository.cs
  BGK.Data/Repositories/ClientRepository.cs
  BGK.Data/Repositories/CompanyRepository.cs
  BGK.Data/Repositories/Interfaces/IAdminRepository.cs
  BGK.Data/Repositories/Interfaces/IClientRepository.cs
  BGK.Data/Repositories/Interfaces/ICompanyRepository.cs
  BGK.Data/Repositories/Interfaces/ILecturerRepository.cs
  BGK.Data/Repositories/Interfaces/IUserRepository.cs
  BGK.Data/Repositories/LecturerRepository.cs
  BGK.Data/Repositories/UserRepository.cs
  BearGoodbyeKolkhoz.API/Controllers/AdminsController.cs
  BearGoodbyeKolkhoz.API/Controllers/ClientsController.cs
  BearGoodbyeKolkhoz.API/Controllers/CompaniesController.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
  BearGoodbyeKolkhoz.API/Controllers/UsersController.cs
  BearGoodbyeKolkhoz.API/Extensions/IServiceProviderExtension.cs
  BearGoodbyeKolkhoz.API/Infrastructure/ErrorHandlerMiddleware.cs
  BearGoodbyeKolkhozProject.Business.Tests/CompanyServiceTests.cs
  BearGoodbyeKolkhozProject.Business.Tests/TestCaseSource/UserTestCaseSource/DeleteUserByIdTestCaseSource.cs
  BearGoodbyeKolkhozProject.Business.Tests/TestCaseSource/UserTestCaseSource/RecoverUserByEmailTestCaseSource.cs
  BearGoodbyeKolkhozProject.Business.Tests/UserServiceTests.cs
  BearGoodbyeKolkhozProject.Data.Tests/AdminTest.cs
  BearGoodbyeKolkhozProject.Data.Tests/CompanyRepositoryTests.cs
  BearGoodbyeKolkhozProject.Data.Tests/LecturerRepositoryTests.cs
  BearGoodbyeKolkhozProject.Data.Tests/TestCaseSources/UserTestCaseSource/ChangeDeleteStatusUserTestCaseSource.cs
  BearGoodbyeKolkhozProject.Data.Tests/TestCaseSources/UserTestCaseSource/GetUserByEmailTestCaseSource.cs
  BearGoodbyeKolkhozProject.Data.Tests/TestCaseSources/UserTestCaseSource/GetUserByIdTestCaseSource.cs
  BearGoodbyeKolkhozProject.Data.Tests/UserRepositoryTests.cs
Labels: bug, new-feature

#91 Bgk 63
  BGK.Business/Services/Interfaces/ILecturerService.cs
  BGK.Business/Services/LecturerService.cs
  BGK.Data/Repositories/Interfaces/ILecturerRepository.cs
  BGK.Data/Repositories/LecturerRepository.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
Labels: bug

#92 Bgk 73
  BearGoodbyeKolkhoz.API/Models/InputModels/AdminInsertInputModel.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/AdminUpdateInputModel.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/AuthInputModel.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/ChangePasswordInputModel.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/RegistrationInputModel.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/AdminOutputModel.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/ClientOutputModel.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/CompanyOutputModel.cs
Labels: new-feature

#95 BGK-63-fix
  BGK.Business/Services/LecturerService.cs
  BGK.Data/Repositories/Interfaces/ILecturerRepository.cs
  BGK.Data/Repositories/LecturerRepository.cs
Labels: bug

#97 Bgk 59 fix
  BGK.Data/Repositories/EventRepository.cs
  BearGoodbyeKolkhoz.API/Controllers/EventsController.cs
Labels: bug

#98 fixs
  BGK.Business/Services/Interfaces/ITrainingService.cs
  BGK.Business/Services/TrainingService.cs
  BGK.Data/Repositories/Interfaces/ITrainingRepository.cs
  BGK.Data/Repositories/TrainingRepository.cs
  BearGoodbyeKolkhoz.API/Controllers/AdminsController.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
  BearGoodbyeKolkhoz.API/Controllers/TrainingsController.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/UserCreateOutputModel.cs
Labels: bug

#99 Dev release v0.2
  BGK.Business/Services/Interfaces/ITrainingService.cs
  BGK.Business/Services/TrainingService.cs
  BGK.Data/Repositories/EventRepository.cs
  BGK.Data/Repositories/Interfaces/ITrainingRepository.cs
  BGK.Data/Repositories/TrainingRepository.cs
  BearGoodbyeKolkhoz.API/Controllers/AdminsController.cs
  BearGoodbyeKolkhoz.API/Controllers/EventsController.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
  BearGoodbyeKolkhoz.API/Controllers/TrainingsController.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/UserCreateOutputModel.cs
Labels: bug, new-feature

#102 BGK-57
  BearGoodbyeKolkhoz.API/Controllers/CompaniesController.cs
Labels: bug

#103 BGK-61
  BearGoodbyeKolkhoz.API/Infrastructure/ErrorHandlerMiddleware.cs
Labels: bug

#104 BGK-74
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
Labels: bug

#89 BGK-81
  BGK.Business/Services/Interfaces/ITrainingService.cs
  BGK.Business/Services/TrainingService.cs
  BearGoodbyeKolkhoz.API/Controllers/TrainingsController.cs
  BearGoodbyeKolkhozProject.Business.Tests/TrainingServiceTests.cs
Labels: bug

#105 Bgk 47, BGK-88, BGK-71, BGK-72
  BGK.Business/Configuration/CheckDublicateEmailForTable.cs
  BGK.Business/Services/AdminService.cs
  BGK.Business/Services/ClientService.cs
  BGK.Business/Services/CompanyService.cs
  BGK.Business/Services/Interfaces/ICompanyService.cs
  BGK.Business/Services/LecturerService.cs
  BGK.Data/Entities/Company.cs
  BGK.Data/Migrations/20220311011456_UnionCompanyAndUser.Designer.cs
  BGK.Data/Migrations/20220311011456_UnionCompanyAndUser.cs
  BGK.Data/Migrations/20220311011721_UnionCompanyAndUser-fix.Designer.cs
  BGK.Data/Migrations/20220311011721_UnionCompanyAndUser-fix.cs
  BGK.Data/Migrations/ApplicationContextModelSnapshot.cs
  BGK.Data/Repositories/CompanyRepository.cs
  BGK.Data/Repositories/Interfaces/ICompanyRepository.cs
  BearGoodbyeKolkhoz.API/Controllers/CompaniesController.cs
  BearGoodbyeKolkhozProject.Business.Tests/CompanyServiceTests.cs
  BearGoodbyeKolkhozProject.Data.Tests/CompanyRepositoryTests.cs
Labels: bug, new-feature

#106 Bgk 93
  BGK.Business/Services/EventService.cs
  BGK.Business/Services/Interfaces/IEventService.cs
  BGK.Data/Repositories/EventRepository.cs
  BGK.Data/Repositories/Interfaces/IEventRepository.cs
  BearGoodbyeKolkhoz.API/Configuration/APIMapperProfile.cs
  BearGoodbyeKolkhoz.API/Controllers/EventsController.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/EventPartialUpdateInputModel.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/EventUpdateInputModel.cs
  BearGoodbyeKolkhoz.API/Properties/launchSettings.json
  BearGoodbyeKolkhozProject.Business.Tests/EventServiceTests.cs
  BearGoodbyeKolkhozProject.Business.Tests/TestCaseSource/EventServiceTestCaseSource/UpdateEventReviewTestCaseSource.cs
  BearGoodbyeKolkhozProject.Data.Tests/EventRepositoryTests.cs
  BearGoodbyeKolkhozProject.Data.Tests/TestCaseSources/EventTestCaseSource/PartialUpdateEventTestCaseSource.cs
Labels: bug

#112 BGK-65
  BGK.Business/Services/EventService.cs
Labels: bug

#108 Bgk 59 part two
  BGK.Data/Repositories/EventRepository.cs
  BearGoodbyeKolkhoz.API/Configuration/APIMapperProfile.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/EventIdOutputInputModel.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/EventOutputModel.cs
  BearGoodbyeKolkhozProject.Business.Tests/EventServiceTests.cs
Labels: bug

#117 Complete validation password with change password
  BGK.Business/Services/ClientService.cs
  BGK.Business/Services/Interfaces/IClientService.cs
  BearGoodbyeKolkhoz.API/Controllers/ClientsController.cs
  BearGoodbyeKolkhoz.API/Models/InputModels/ChangePasswordInputModel.cs
Labels: new-feature

#124 BGK-100
  BGK.Business/Services/LecturerService.cs
  BearGoodbyeKolkhoz.API/Controllers/LecturersController.cs
  BearGoodbyeKolkhoz.API/Models/OutputModels/TrainingOutputModel.cs
Labels: bug
